//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobTheGrader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Assignments
    {
        public int Course_AssignmentsID { get; set; }
        public int AssignmentID { get; set; }
        public int CourseInstanceID { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual CourseInstance CourseInstance { get; set; }
    }
}
