//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobTheGrader.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.SUBMISSIONs = new HashSet<SUBMISSION>();
        }
    
        public int QuestionID { get; set; }
        public int AssignmentID { get; set; }
        [Display(Name = "Question Type")]
        public int QuestionTypeID { get; set; }
        public string Title { get; set; }
        [Display(Name = "Maximum Tries")]
        public int MaximumTries { get; set; }
        [Display(Name = "Maximum Grade")]
        public int MaximumGrade { get; set; }
        [Display(Name = "Output")]
        [DataType(DataType.MultilineText)]
        public string output { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMISSION> SUBMISSIONs { get; set; }
    }
}
