//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobTheGrader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Permissions
    {
        public int Role_PermissionID { get; set; }
        public int UserRoleID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
